### ISSUE TITLE
[FEA]: Remove CDP (RDC) architecture filtering logic from Thrust/CUB tests

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#1137]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

General CCCL

### Is your feature request related to a problem? Please describe.

Thrust/CUB have tests that explicitly exercise "CUDA Dynamic Parallelism (CDP)", i.e., launching a kernel from within another kernel. 

These tests were added at a time when `cudaDeviceSynchronize()` from device code was supported (i.e., CDPv1). 

However, CDPv1 has been replaced with CDPv2 that no longer supports device-side synchronization. Furthermore, newer architectures no longer support CDPv1 (e.g., sm90). As a result, Thrust/CUB [implemented cmake logic to filter](https://github.com/NVIDIA/cccl/blob/b421cc783b12f4d1a72183cf8c143eb5c2dc34ca/cub/cmake/CubCudaConfig.cmake#L18-L21) out architectures that don't support CDPv1, [which has lead to issues.](https://github.com/NVIDIA/cccl/issues/219) 

With the introduction of CDPv2, CUB/Thrust were refactored to no longer rely on device-side synchronization.
- CUB was refactored to remove synchronization and use tail kernels launches instead
- Synchronization could not be removed from Thrust algorithms, and so Thrust was updated such that `thrust::device` in device code fell back to `thrust::seq`

As a result, we no longer have tests that exercise CDPv1. Therefore, we no longer need to filter out the architecture list. 

### Describe the solution you'd like

Remove the architecture filtering logic from Thrust/CUB cmake files. 

Thrust/CUB tests _should_ all work, but there may be lingering issues to clean up as a result of removing the filtering logic. 

### Tasks
- [ ] Remove CDP filtering/target logic from CUB cmake
- [ ] Remove CDP filtering/target logic from Thrust cmake
