### ISSUE TITLE
[FEA]: Implement `<ranges>` concepts and CPOs and backport to C++17

### ISSUE THREAD

**Issue by miscco** [NVIDIA/cccl#1149]
```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/1195
- [ ] https://github.com/NVIDIA/cccl/issues/1207
- [ ] https://github.com/NVIDIA/cccl/issues/1255
- [ ] https://github.com/NVIDIA/cccl/issues/1294
- [ ] https://github.com/NVIDIA/cccl/issues/1300
- [ ] https://github.com/NVIDIA/cccl/issues/1312
- [ ] https://github.com/NVIDIA/cccl/issues/1329
- [ ] https://github.com/NVIDIA/cccl/issues/1337
- [ ] https://github.com/NVIDIA/cccl/issues/1363
- [ ] https://github.com/NVIDIA/cccl/issues/1370
- [ ] https://github.com/NVIDIA/cccl/issues/1376
- [ ] https://github.com/NVIDIA/cccl/issues/1386
- [ ] https://github.com/NVIDIA/cccl/issues/1416
```

**Comment by miscco** [comment]
All relevant features have been implemented 🎉
