### ISSUE TITLE
[FEA]: Unify CMake infrastructure across projects.

### ISSUE THREAD

**Issue by alliepiper** [NVIDIA/cccl#1204]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

General CCCL

### Is your feature request related to a problem? Please describe.

There is currently a lot of redundancy in the CMake build system across subprojects that can be consolidated to reduce maintenance burden and smooth out rough edges.

```[tasklist]
### Tasks
- [ ] Determine full list of redundant infrastructure to consolidate.
- [ ] Remove ability to configure individual subprojects without configuring CCCL (would simplify things greatly).
- [ ] Move all install rules to top-level project.
- [ ] Move all find_package configs to top-level project.
- [ ] Move tests/examples to top-level projects?
- [ ] https://github.com/NVIDIA/cccl/issues/1205
```

**Comment by alliepiper** [comment]
Closing as this has been consumed by #2366.
