### ISSUE TITLE
Port `thrust::cuda_cub::parallel_for` to CUB

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#1231]
```[tasklist]
### Tasks
- [x] cub::DeviceFor::ForEach
- [x] cub::DeviceFor::Bulk (implicit counting iterator input)
- [x] cub::DeviceFor::ForEachCopy
- [x] Decide what to do with temporary storage
- [x] Decide if we should use occupancy calculator for determining launch properties
```
