### ISSUE TITLE
[DOC]: Monorepo user guide and examples

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#130]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Is this for new documentation, or an update to existing docs?

New

### Describe the incorrect/future/missing documentation

Users will want to know how they should use CCCL from the new monorepo. We should provide a guide linked from our README that shows various use cases. We should steer people towards using cmake and CPM whenever possible. 

As an example, here's a similar doc I wrote for the stdexec repo: https://github.com/nvidia/stdexec#how-to-get-stdexec

```[tasklist]
### Tasks
- [x] Add a "How to get CCCL" section to README
- [x] Add a "Using CCCL" section to README
- [ ] https://github.com/NVIDIA/cccl/issues/131
```

**Comment by jrhemstad** [comment]
Closed by https://github.com/NVIDIA/cccl/pull/291
