### ISSUE TITLE
[EPIC] Host-only functionality and testing

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#1374]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

General CCCL

### Is your feature request related to a problem? Please describe.

As a user of CCCL code, there are certain headers and features that I'd like to be able to use independent of compiling with `nvcc`. In other words, I'd like to know which headers and functionality can be used with only a host compiler (i.e., no `nvcc`). 

I'd expect CCCL to clearly document guarantees which headers/features should work in host-only TUs. Furthermore, I'd expect CCCL to thoroughly test these guarantees as part of its CI testing. 

### Describe the solution you'd like

```[tasklist]
### Tasks
- [ ] Document guarantees about host-only support for `libcudacxx` headers
- [ ] Ensure CI testing for supported `libcudacxx` headers in host-only TUs
- [ ] Document guarantees about host-only support for `Thrust` headers
- [ ] Ensure CI testing for supported `thrust` headers in host-only TUs
- [ ] Document (lack of) guarantees about host-only support for `CUB` headers
```

**Comment by bernhardmgruber** [comment]
Here is the wording in the [current documentation](https://nvidia.github.io/cccl/libcudacxx/#summary-std-cuda-and-cuda-std) of libcu++:

-  ``std::`` / ``<*>``: This is your host compiler's Standard Library that works in ``__host__`` code only, although you
   can use the ``--expt-relaxed-constexpr`` flag to use any ``constexpr`` functions in ``__device__`` code.
   libcu++ does not replace or interfere with host compiler's Standard Library.
-  ``cuda::std::`` / ``<cuda/std/*>``: Conforming implementations of facilities from the Standard Library that work in
   ``__host__ __device__`` code.
-  ``cuda::`` / ``<cuda/*>``: Conforming extensions to the Standard Library that work in ``__host__ __device__`` code.
-  ``cuda::device`` / ``<cuda/device/*>``: Conforming extensions to the Standard Library that work only in
   ``__device__`` code.
-  ``cuda::ptx``: C++ convenience wrappers for inline PTX (only usable in ``__device__`` code).

I discussed with @wmaxey that "works in ``__host__`` code" implies that it can be compiled by a non-CUDA compiler like g++. We should add a corresponding clarifying comment to the documentation of libcu++.
