### ISSUE TITLE
Identify CUB algorithms that do/do not support large inputs

### ISSUE THREAD

**Issue by elstehle** [NVIDIA/cccl#1408]
In CUB we want to converge to a uniform way of handling the offset types. Currently there are predominantly three ways an algorithm determines the offset type that is used within its kernel(s): (1) use the type the user provided for the `num_items` parameter, (2) use `int` as the offset type, and (3) use `uint32_t` if `num_items`'s type is four bytes or less and use `uint64_t` otherwise.

[This comment](https://github.com/NVIDIA/cub/issues/212#issuecomment-929547156) summarizes the state we want to converge to. I.e., preferably use option (3). 

We should summarize the state of determining the offset type for all algorithms used in CUB:

- [x] Provide a list of device-scope algorithms currently present in CUB ([see here](https://github.com/NVIDIA/cccl/issues/50#issuecomment-1956325564))
- [x] For each algorithm, summarize the dispatch mechanism currently used ([see here](https://github.com/NVIDIA/cccl/issues/50#issuecomment-1956325564))
- [x] Check if we test the algorithm for
  - [x] inputs larger than `std::numeric_limits<uint32_t>::max()` ([see here](https://github.com/NVIDIA/cccl/issues/50#issuecomment-1956325564))
  - [x] inputs close to `std::numeric_limits<OffsetT>::max()` to make sure we don't run into integer overflows during offset  computation within the kernels ([see here](https://github.com/NVIDIA/cccl/issues/50#issuecomment-1956325564))
