### ISSUE TITLE
[FEA]: Expose new `StencilIf` functionality in `cub::DeviceSelect` 

### ISSUE THREAD

**Issue by elstehle** [NVIDIA/cccl#1409]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

CUB

### Is your feature request related to a problem? Please describe.

[thrust::copy_if](https://nvidia.github.io/cccl/thrust/api/groups/group__stream__compaction.html#function-copy-if) has an overload that takes a stencil iterator, `stencil`, and a predicate, `pred`. The algorithm copies elements from the range `[first,last)` to a range beginning at `result`, except that any element whose corresponding `stencil` element causes `pred` to be `false` is not copied.

```
copy_if(InputIterator1 first,
  InputIterator1 last,
  InputIterator2 stencil,
  OutputIterator result,
  Predicate pred);
```

As part refactoring `thrust::copy_if` to use `cub::DeviceSelect` ([issue](https://github.com/NVIDIA/cccl/issues/1263), [PR](https://github.com/NVIDIA/cccl/pull/1379)), this functionality was added to the algorithm implementation (i.e., `AgentSelectIf`) in CUB _but was not yet exposed in the corresponding `DeviceSelect` interface of CUB_.

We want to expose this new functionality in `DeviceSelect` and add tests for this.

### Tasks
- [ ] Add new interface for `cub::DeviceSelect::StencilIf`
- [ ] Add documentation and example for `cub::DeviceSelect::StencilIf` 
- [ ] Add tests for `cub::DeviceSelect::StencilIf` 

### Describe the solution you'd like

Expose new functionality via `cub::DeviceSelect::StencilIf` interface.
