### ISSUE TITLE
Add support for large `num_items` to `device_partition.cuh`

### ISSUE THREAD

**Issue by elstehle** [NVIDIA/cccl#1437]
Currently blocked by https://github.com/NVIDIA/cccl/issues/50

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/1614
- [x] make the type of `num_items` a template parameter of `DevicePartition` algorithms
- [x] determine approach to be used for offset type handling per https://github.com/NVIDIA/cccl/issues/50 for `DevicePartition`
- [ ] https://github.com/NVIDIA/cccl/issues/2238
- [x] Benchmark changes against main for small, medium, and very large number of items
```
