### ISSUE TITLE
Determine and finalize design for large input support in CUB

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#1454]
The desired outcome is a document that includes the following:
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/1787
- [ ] https://github.com/NVIDIA/cccl/issues/1771
- [ ] https://github.com/NVIDIA/cccl/issues/2055
- [ ] https://github.com/NVIDIA/cccl/issues/2136

**Comment by bhack** [comment]
Is there any public progress on the task?

**Comment by elstehle** [comment]
> Is there any public progress on the tasks?

Thank you for your interest in the issue, @bhack, and sorry for the late reply. We are currently exploring potential solutions and hope to have a proposal on how to move forward by next week.

**Comment by bhack** [comment]
Thanks for the update. In the meantime do you know if we will have a CUDA official release to use the extended interface in https://github.com/NVIDIA/cccl/pull/1379 so that we could try to implement a workaround like in your test?.

**Comment by elstehle** [comment]
> do you know if we will have a CUDA official release to use the extended interface in https://github.com/NVIDIA/cccl/pull/1379

@bhack, https://github.com/NVIDIA/cccl/pull/1379 was included in CCCL 2.4, which is included in Cuda Toolkit 12.5.

**Comment by elstehle** [comment]
A description of possible approaches can be found in https://github.com/NVIDIA/cccl/issues/1771.
The approach we're taking for each specific algorithm is maintained in the table in https://github.com/NVIDIA/cccl/issues/50#issuecomment-1956325564
