### ISSUE TITLE
[FEA]: Allow multiple benchmarks in a single tuning

### ISSUE THREAD

**Issue by senior-zero** [NVIDIA/cccl#151]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

CUB

### Is your feature request related to a problem? Please describe.

Currently, the tuning infrastructure only supports a single benchmark per file. This makes it difficult to organize a search process on disjoint sets of workloads produced by Cartesian product of runtime axes.  

### Describe the solution you'd like

```[tasklist]
### Tasks
- [x] Allow multiple benchmarks in a single tuning
- [x] Extend batched memcpy benchmark with new workload covering small number of very large segments
```

### Describe alternatives you've considered

We could use `skip` feature along with including all possible options in a single Cartesian product, but this creates a lot of noise.
