### ISSUE TITLE
[FEA]: Use P2322R6 to determine accumulator type in Thrust

### ISSUE THREAD

**Issue by senior-zero** [NVIDIA/cccl#153]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Thrust

### Is your feature request related to a problem? Please describe.

We adopted P2322R6 scheme in CUB (https://github.com/NVIDIA/cub/issues/428), but Thrust still uses accumulator types that are surprising to users and do not follow general C++ rules like integer promotion. 

### Describe the solution you'd like

We should decide if we'd like to proceed with P2322R6 adoption in Thrust and follow CUB scheme of selecting accumulator types. 

```[tasklist]
### Tasks
- [ ] Decide if the silent change of accumulator type is breaking
- [ ] Prepare a list of standard algorithms that specify accumulator types 
- [ ] Consider preparing a paper to adopt P2322R6 to standard algorithms
``` 

CC: @jrhemstad @dkolsen-pgi

**Comment by fbusato** [comment]
I did a quick investigation to understand the current status.

First of all, the adopting of [P2322](https://wg21.link/P2322) is considered a **breaking change** for the following reasons:

- The resulting data type (and signature) is affected
- The result of the computation can be different

The following functionalities (all overloadings) need to update their behavior. (`X<N>`: num overloadings)

-  `inclusive_scan/esxlusive_scan` X12
-  `inner_product` X3
-  `transform_reduce` X2
-  `reduce` X6
