### ISSUE TITLE
[DOC]: Update Contributing Guide/CI Overview to include information about pre-commit

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#1623]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Is this for new documentation, or an update to existing docs?

New

### Describe the incorrect/future/missing documentation

As a contributor to CCCL, I'd like to know whatever it is I need to know to ensure my contributions are formatted correctly and will pass the CI format check. 

```[tasklist]
### Tasks
- [ ] Add "Pre-Commit Linters" section to contributing guide with top-level overview of precommit and subsection for clang-format
- [ ] Update CI Overview to add section about pre-commit.ci 
``` 

The desired outcome is that if the `pre-commit.ci` job fails, people should have somewhere to go to tell them how to fix it. This should include:
- Information about how to run formatting locally (whether with VSCode or pre-commit directly) 
- Information about how to use the `pre-commit.ci autofix` comment on a PR to automatically apply `pre-commit` linters

**Comment by bdice** [comment]
I opened https://github.com/NVIDIA/cccl/pull/1627 with an attempt at this documentation. I copied a lot of it from cuDF.
