### ISSUE TITLE
Implement cuda.parallel Python module

### ISSUE THREAD

**Issue by wmaxey** [NVIDIA/cccl#1999]
We've just merged `cuda.cooperative` Python module. Next step is prototyping `cuda.parallel` module with host-side (device-level) parallel algorithms. Prototyping is scoped to device reduction. Remaining algorithms are about to be tracked by standalone issues.

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/2230
- [ ] https://github.com/NVIDIA/cccl/issues/2232
- [ ] https://github.com/NVIDIA/cccl/issues/2268
- [ ] https://github.com/NVIDIA/cccl/issues/2235
- [ ] https://github.com/NVIDIA/cccl/issues/2236
- [ ] https://github.com/NVIDIA/cccl/issues/2280
- [ ] https://github.com/NVIDIA/cccl/issues/2295
- [ ] https://github.com/NVIDIA/cccl_private/issues/209
```

**Comment by gevtushenko** [comment]
cuda.parallel module was introduced to CCCL repo and CI. Further work on cuda.parallel will be tracked by a different issue.
