### ISSUE TITLE
Modern versions of cudaMemset and cudaMemcpy

### ISSUE THREAD

**Issue by griwes** [NVIDIA/cccl#2000]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/2144
- [ ] Initial design proposal for cuda::memcpy
- [ ] https://github.com/NVIDIA/cccl/issues/2912

**Comment by bernhardmgruber** [comment]
I am curious how this isn't `thrust::fill` and `thrust::copy`. Is there already a sketch of the design available somewhere?

**Comment by pciolkosz** [comment]
Implemented in [https://github.com/NVIDIA/cccl/pull/2932](url) and [https://github.com/NVIDIA/cccl/pull/2608](url)
