### ISSUE TITLE
[EPIC]: Atomics Improvements

### ISSUE THREAD

**Issue by wmaxey** [NVIDIA/cccl#2047]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

libcu++

### Is your feature request related to a problem? Please describe.

Atomics today are missing critical features. This is a general roadmap and improvement checklist.

### Describe the solution you'd like

A non-exhaustive list of issues and things that need to be implemented:

- [ ] Improved codegen for emitting inline PTX.
- [ ] 128b atomics.
- [ ] 8b/16b atomics.
- [ ] `volatile T` MMIO support. This may depend on changes from compiler side.
- [ ] C++26 changes.
- [ ] Improved testing for atomics and heterogeneous coverage.
