### ISSUE TITLE
Higher-level, `cuda::vector<T, Properties...>` (like `thrust::host_vector/device_vector`)

### ISSUE THREAD

**Issue by miscco** [NVIDIA/cccl#2057]
### Tasks
- [x] Decide if resource_ref<> means resource_ref<host_accessible>
- [ ] https://github.com/NVIDIA/cccl/issues/2058
- [ ] https://github.com/NVIDIA/cccl/issues/2059
- [ ] https://github.com/NVIDIA/cccl/issues/2886
- [ ] https://github.com/NVIDIA/cccl/issues/2887
