### ISSUE TITLE
Add support for large `num_items` to `device_scan.cuh`

### ISSUE THREAD

**Issue by elstehle** [NVIDIA/cccl#2062]
```[tasklist]
### Tasks
- [x] Add tests for large number of items in `DeviceScan` (completed by https://github.com/NVIDIA/cccl/pull/1830)
- [x] Make the type of `num_items` a template parameter of `DeviceScan` algorithms
- [x] Use `choose_offset_t` as offset type within kernels of `DeviceScan`
- [x] Benchmark performance against main on V100 and H100
- [x] Switch tests for large number of items to use `DeviceScan` interface instead of the helper functions that use `DispatchScan` (which were introduced by https://github.com/NVIDIA/cccl/pull/1830)
- [x] Remove the list of `offset_types` that we test for in `DeviceScan` to only mimic the 32- and 64-bit actually used in `DeviceScan`
- [x] Adapt `thrust::scan` to have the same offset types used in the device interface of CUB
```
