### ISSUE TITLE
Create `cub::DeviceTransform`

### ISSUE THREAD

**Issue by bernhardmgruber** [NVIDIA/cccl#2091]
See #1947 for motivation, concerns and overall goals. We need a new CUB algorithm for transforming a set of input streams to an output stream and rebase `thrust::transform` on top of this. This ensures we stay close to the SOL of recent and upcoming GPU architectures. Several new transformation algorithms have been developed by @ahendriksen which will be upstreamed into CCCL this way.

As a first milestone, a working `cub::DeviceTransform` should be built, tuned, reviewed and merged. To validate the design `thrust::transform` should also be ported. As a benchmark, BabelStream will be used.

```[tasklist]
### Tasks until first stable version
- [x] Build a prototype (offline) validating this approach
- [x] Ensure we have enough benchmarks for `thrust::transform`, including BabelStream
- [x] Add `cub::DeviceTransform` supporting N input streams and 1 output stream
- [x] Support non-contiguous iterators
- [x] Support non-trivially-copyable types
- [x] Add tuning benchmarks for cub::DeviceTransform
- [x] Add the current thrust implementation as a fallback algorithm to `cub::DeviceTransform`s, so tuning can include it
- [x] Tune `cub::DeviceTransform` to surpass the current `cub::DeviceFor`-based implementation on relevant GPUs
- [x] Make the prefetch kernel support non-contiguous iterators and drop falling back to cub::DeviceFor
- [x] Minimize the amount of kernels compiled
- [x] API usage examples in documentation
- [x] Avoid any out-of-bounds buffer accesses of the initial kernels
- [x] Ensure performance surpasses the current `thrust::transform` implementation (`cub::DeviceFor`)
```
