### ISSUE TITLE
Codify compute capabilities as statically and dynamically queryable traits

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#2097]
As a CUDA C++ developer, I often need to write code specialized for different compute capabilities.

One of the things I need to deal with are various properties differing based on the architecture/compute capability. For example, I may need to query the maximum amount of shared memory allowed per SM for a given architecture. 
![image](https://github.com/user-attachments/assets/7ec2837c-200b-407d-8fc4-9724676e3a19)

I would like a standard and convenient way to query this information both statically and dynamically.

For static queries, I could imagine doing something similar to `<traits>` like:
```
#include <cuda/device_traits>
static_assert( cuda::max_registers_per_thread_v<80> == 255);
```

Unlike traits, I want to be able to query this information dynamically as well as I may need to make runtime decisions based on what GPU is present in the system:
```
auto CC = cuda::get_device_compute_capability( /*some device handle*/ );
assert( cuda::max_registers_per_thread(CC) == 255);
```

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/2270
- [ ] https://github.com/NVIDIA/cccl/issues/2083
- [ ] https://github.com/NVIDIA/cccl/issues/2315
```

**Comment by pciolkosz** [comment]
There are still smaller optimizations we can do, but that is beyond MVP scope, closing
