### ISSUE TITLE
[FEA]: Improve performance of `thrust::all_of`.

### ISSUE THREAD

**Issue by gonidelis** [NVIDIA/cccl#2113]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Thrust

### Is your feature request related to a problem? Please describe.

Addresses and provides a roadmap for #720. The current idea is that we explore whether a new `cub::DeviceFind::FindIf` implementation could be used for a twofold cause: a) port `thrust::find` to CUB and b) use a common CUB implementation for `thrust::all_of` that utilizes early exit.

### Describe the solution you'd like

```[tasklist]
### Tasks
- [ ]  Build a prototype CUB `cub::DeviceFind::FindIf` kernel that [combines performant reduction and early exit](https://github.com/NVIDIA/cccl/pull/1870#discussion_r1642007649).
- [ ] Benchmark and optimize `cub::DeviceFind::FindIf` against `thrust::find_if`, `thrust::count_if`.
- [ ]  Port `thrust::all_of` to `cub::DeviceFind::FindIf`.
- [ ] Port `thrust::find` to `cub::DeviceFind::FindIf`.
```

**Comment by gonidelis** [comment]
`thrust::all_of` now dispatches all the way down to `cub::FindIf`, we can close
