### ISSUE TITLE
Publish `cuda::cooperative` Python package

### ISSUE THREAD

**Issue by leofang** [NVIDIA/cccl#2148]
```[tasklist]
### Tasks
- [ ] Add a CI workflow to use `cibuildwheels` to build and test the generated wheel
- [ ] Publish a wheel to PyPI.org (it should be a `py3`/noarch wheel)
- [ ] Post an announcement to Numba discourse
- [ ] Publish a conda package to conda-forge
```

**Comment by bdice** [comment]
@leofang Happy to help review this packaging work! Please tag me on any PRs. 👍

**Comment by shwina** [comment]
Closing this in favor of https://github.com/NVIDIA/cccl/issues/4590.
