### ISSUE TITLE
[DOC]: Integrate Python docs into the root CCCL documentation

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#2155]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Is this for new documentation, or an update to existing docs?

New

### Describe the incorrect/future/missing documentation

CCCL [documentation](https://nvidia.github.io/cccl/) currently has the following structure:
- libcu++
- Thrust
- CUB
- Cuda Experimental

We have to embed Python documentation into this tree. To do that, we can consider adopting the following structure:
- CUDA C++ 
   - libcu++
   - Thrust
   - CUB
   - Cuda Experimental
- CUDA Python
   - cuda.cooperative

This structure requires authoring a new landing page with generic Core Libraries description that is not specific to C++ or Python. So the issue involves:
```[tasklist]
### Tasks
- [ ] Upload Python docs as an artifact in GitHub [actions](https://github.com/NVIDIA/cccl/blob/2600135d12e74e5a022eb3038a90d71a9e5fe2ac/.github/actions/docs-build/action.yml#L36-L37)
- [ ] Restructure root [toctree](https://github.com/NVIDIA/cccl/blob/2600135d12e74e5a022eb3038a90d71a9e5fe2ac/docs/index.rst?plain=1#L4-L11) to include Python
- [ ] Replace [landing CCCL page](https://github.com/NVIDIA/cccl/blob/main/docs/index.rst) with language-independent CCCL description
```
