### ISSUE TITLE
FEA: Introduce CMake / CI infrastructure for cccl/c

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#2235]
We recently merged another CCCL subproject in cccl/c. The CMake part of the project is barely functional, and needs some work to get it into consistent state with the rest of the CCCL. Right now, the project is enabled with `CCCL_ENABLE_C`. If the work on CMake part changes enablement macro or target names, it should be reflected in the preset file and https://github.com/NVIDIA/cccl/blob/main/python/cuda_parallel/setup.py as well. 

CCCL/C also needs CI infrastructure. In terms of dependencies, CCCL/C depends on libcu++, thrust, and CUB and needs GCC 13. We can scope testing to linux for now. 

```[tasklist]
### Tasks
- [x] Setup/improve CMake target and presets for cccl/c
- [x] Add CI scripts for build and test of CCCL/c
- [x] Add CI jobs that build cccl/c binary and run tests
```
