### ISSUE TITLE
Port `thrust::transform` to use `cub::DeviceTransform`

### ISSUE THREAD

**Issue by bernhardmgruber** [NVIDIA/cccl#2263]
Once #2086 is merged, `thrust::transform` should be ported to use `cub::DeviceTransform`.

```[tasklist]
### Tasks
- [x] Design an opt-in for function objects to express they do not require address stability
- [x] Port `thrust::transform` to `cub::DeviceTransform`
- [x] Ensure zip_iterators passed to `thrust::transform` are decomposed and optimized
- [x] Ensure we have enough benchmarks for `thrust::transform`, including BabelStream
- [x] Discuss and finalize the design of the address stability opt-in
- [ ] https://github.com/NVIDIA/cccl/issues/2402
```
