### ISSUE TITLE
[DOC]: Clarity check of CUB device-scope docs

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#2323]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Is this for new documentation, or an update to existing docs?

New

### Describe the incorrect/future/missing documentation

```[tasklist]
### Tasks
- [ ] cub/cub/device/device_adjacent_difference.cuh
- [ ] cub/cub/device/device_copy.cuh
- [ ] cub/cub/device/device_for.cuh
- [ ] cub/cub/device/device_histogram.cuh
- [ ] cub/cub/device/device_memcpy.cuh
- [ ] cub/cub/device/device_merge.cuh
- [ ] cub/cub/device/device_merge_sort.cuh
- [ ] cub/cub/device/device_partition.cuh
- [ ] cub/cub/device/device_radix_sort.cuh
- [ ] cub/cub/device/device_reduce.cuh
- [ ] cub/cub/device/device_run_length_encode.cuh
- [ ] cub/cub/device/device_scan.cuh
- [ ] cub/cub/device/device_segmented_radix_sort.cuh
- [ ] cub/cub/device/device_segmented_reduce.cuh
- [ ] cub/cub/device/device_segmented_sort.cuh
- [ ] cub/cub/device/device_select.cuh
- [ ] cub/cub/device/device_spmv.cuh
```
