### ISSUE TITLE
[DOC]: Clarity check of CUB block-scope docs

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#2324]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Is this for new documentation, or an update to existing docs?

New

### Describe the incorrect/future/missing documentation

We receive a number of reports on documentation bugs. Some of these are caused by copy-paste. But more importantly, some of the docs are just difficult to understand. We should make a pass through CUB block-scope docs to see if we can preemptively improve clarity and fix bugs to save users some time. 

```[tasklist]
### Tasks
- [ ] cub/cub/block/block_adjacent_difference.cuh
- [ ] cub/cub/block/block_discontinuity.cuh
- [ ] cub/cub/block/block_exchange.cuh
- [ ] cub/cub/block/block_histogram.cuh
- [ ] cub/cub/block/block_load.cuh
- [ ] cub/cub/block/block_merge_sort.cuh
- [ ] cub/cub/block/block_radix_rank.cuh
- [ ] cub/cub/block/block_radix_sort.cuh
- [ ] cub/cub/block/block_raking_layout.cuh
- [ ] cub/cub/block/block_reduce.cuh
- [ ] cub/cub/block/block_run_length_decode.cuh
- [ ] cub/cub/block/block_scan.cuh
- [ ] cub/cub/block/block_shuffle.cuh
- [ ] cub/cub/block/block_store.cuh
```
