### ISSUE TITLE
[FEA]: Consolidate shared CMake infrastructure.

### ISSUE THREAD

**Issue by alliepiper** [NVIDIA/cccl#2366]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Thrust

### Is your feature request related to a problem? Please describe.

Our projects have a lot of redundant cmake code and dependency fetches. These should be centralized and de-duplicated.

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/2385
- [ ] https://github.com/NVIDIA/cccl/issues/2387
- [x] Add a `cccl_add_subdir_helper` that reduces redundancy in our `*AddSubdir.cmake` files.
- [x] Move all cmake packages to `cccl/lib/cmake/{project}`
- [x] Move all install rules to `cccl/cmake/install/{project}.cmake`
- [x] Add a `cccl_generate_header_tests` function that creates header tests from a list of sources + compiler definitions.
- [x] Revamp cudax samples to be consistent with the rest of the subproject examples.
- [ ] https://github.com/NVIDIA/cccl/issues/2350
- [ ] https://github.com/NVIDIA/cccl/issues/2494
- [ ] https://github.com/NVIDIA/cccl/issues/2615
- [ ] Enable use of `cccl.compiler_interface_cppXX` targets in libcudacxx
```
