### ISSUE TITLE
[FEA]: Update to latest 23.08 devcontainers

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#245]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Infrastructure

### Is your feature request related to a problem? Please describe.

We are currently using the 23.06 devcontainer images from https://github.com/rapidsai/devcontainers and we should update to the 23.08 images. 

### Describe the solution you'd like

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/241
- [ ] https://github.com/rapidsai/devcontainers/issues/97
- [ ] Update to use CUDA 12.2 over CUDA 12.1 images
- [ ] Update to 23.08 images
```
