### ISSUE TITLE
[EPIC] Refactor all Thrust algorithms to use CUB

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#25]
```[tasklist]
- [ ] Define list of all Thrust algorithms that should be refactored to use CUB
- [ ] https://github.com/NVIDIA/cccl/issues/1210
- [ ] Use `cub::DeviceReduce` for `thrust::reduce`
- [ ] https://github.com/NVIDIA/cccl/issues/1263
- [ ] Use CUB implementation for extrema algorithms
- [ ] Use CUB implementation for partition
- [ ] Use CUB implementation for reduce_by_key
```

**Comment by jrhemstad** [comment]
Closing this in favor of https://github.com/NVIDIA/cccl/issues/26 which we'll use for tracking both moving Thrust kernels to CUB and refactoring Thrust algorithms to use CUB kernels.
