### ISSUE TITLE
Migrate CUB's `c2h` test library to the CCCL level to facilitate reuse.

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#2615]
```[tasklist]
### Tasks
- [x] Migrate c2h headers
- [x] Write cmake infra
- [x] Rename CUB_TEST etc macros
- [x] inspect_change.sh dependencies
- [x] Look into what's going on with the *other* c2h in cccl.c.parallel.
- [x] Figure out `test_util_vec.cuh` (make copy for c2h?)
- [x] Integrate recent CUDAToolKit changes for nvhpc
```
