### ISSUE TITLE
[FEA]: Add new images with extra CUDA libs for STF and MatX

### ISSUE THREAD

**Issue by alliepiper** [NVIDIA/cccl#2630]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Infrastructure

### Is your feature request related to a problem? Please describe.

The most straightforward route would be to install the extra CUDA libs at runtime by customizing features in the `.devcontainer` file, for example: https://github.com/rapidsai/raft/blob/branch-24.12/.devcontainer/cuda12.5-pip/devcontainer.json#L18-L24

### Describe the solution you'd like

```[tasklist]
### Tasks
- [ ] Get local devcontainer with features working
- [ ] Update the `make_devcontainers.sh` script to generate `cudaExtra` devcontainers.
- [ ] Enable CI jobs for CUDASTF with optional mathlibs enabled.
- [ ] https://github.com/NVIDIA/cccl/issues/2264
```
