### ISSUE TITLE
[FEA]: Relax shuffle-based warp exchange requirements

### ISSUE THREAD

**Issue by senior-zero** [NVIDIA/cccl#271]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

CUB

### Is your feature request related to a problem? Please describe.

https://github.com/NVIDIA/cccl/pull/256 introduced shuffle-based warp exchange algorithm that supports cases where items per threads is equal to the number of threads and is a power-of-two number. Alternative [algorithms](https://github.com/bryancatanzaro/trove) support `n` threads containing `m` items. Apart from that, we could relax the requirement on the item types to be any trivially-copyable type fitting into 64 bits. 

### Describe the solution you'd like

We should:

```[tasklist]
### Tasks
- [ ] Support non-square cases in shuffle-based warp exchange algorithm
- [ ] Support trivially-copyable types that can fit into 64 bits in shuffle-based warp exchange algorithm
```
