### ISSUE TITLE
[EPIC] CUB Test Catch2 Migration

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#28]
In order to improve and simplify CUB testing, we would like to overhaul all of CUB's unit tests with a new and improved design built on top of Catch2.

- [ ] https://github.com/NVIDIA/cub/pull/365
- [ ] https://github.com/NVIDIA/cub/pull/660
- [ ] https://github.com/NVIDIA/cub/pull/654
- [ ] https://github.com/NVIDIA/cub/pull/616
- [ ] https://github.com/NVIDIA/cccl/issues/29
- [ ] Remove old tests
- [ ] Remove `test_util.h` & `mersenne.h`

**Comment by alliepiper** [comment]
Subtasks complete.
