### ISSUE TITLE
[EPIC] Port CUB device-scope algorithm tests to use Catch2

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#29]
### Tasks
- [x] Split this list up into what can be done for 2.2 vs future
- [ ] https://github.com/NVIDIA/cccl/issues/85
- [ ] https://github.com/NVIDIA/cccl/issues/86
- [ ] https://github.com/NVIDIA/cccl/issues/87
- [ ] https://github.com/NVIDIA/cccl/issues/1798

**Comment by jrhemstad** [comment]
@elstehe

**Comment by alliepiper** [comment]
All subtasks complete.
