### ISSUE TITLE
[FEA]: Vectorize memory operations in CUB algorithms

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#307]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

CUB

### Is your feature request related to a problem? Please describe.

Some CUB algorithms (histogram and reduce) rely on vectorized loads. Other CUB algorithms demonstrate poor memory utilization when processing 1-2 byte types. 

#### U8

![U8](https://github.com/NVIDIA/cccl/assets/9890394/c71f992e-0c87-4c60-a875-73ceec714799)

#### U16

![U16](https://github.com/NVIDIA/cccl/assets/9890394/65c24129-96b8-43c0-ae53-9d717d3f0a47)

### Describe the solution you'd like

We should consider vectorizing memory operations in the following algorithms:

### Tasks
- [ ] Vectorize memory operations in run length encode
- [ ] Vectorize memory operations in partition
- [ ] https://github.com/NVIDIA/cccl/issues/310
- [ ] Vectorize memory operations in scan
- [ ] Vectorize memory operations in reduce by key
