### ISSUE TITLE
Make build_* scripts take no arguments by default

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#314]
For convenience, I would like the build scripts to not require any arguments and use logical defaults by default.

For the host compiler, it should be already provided by the CXX/CC envvars.

For C++ dialect, we can just use C++17 since it is supported by all the host compilers/CTKs.

For GPU architecture, ideally we'd be able to use CMAKE_CUDA_ARCHITECTURES=native and rely on cmake/nvcc's automatic architecture detection.

However, libcudacxx/cub/thrust's cmake configs do not currently support using this.

```[tasklist]
### CMAKE_CUDA_ARCHITECTURE
- [ ] https://github.com/NVIDIA/cccl/issues/279
- [ ] https://github.com/NVIDIA/cccl/issues/278
``` 
```[tasklist]
### Tasks
- [ ] Update script to no longer require taking arguments
- [ ] Explore making a single build script that takes a cmake preset
```

**Comment by jrhemstad** [comment]
This is done as of the transition to using cmake presets defaulting to using CXX and CUDAHOSTCXX as well as the cuda architectures. It no longer depends on supporting the `native` arch option.
