### ISSUE TITLE
Port existing docs to Sphinx

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#315]
CUB docs were updated to use the new rst/sphinx docs system. We should update Thrust/libcudacxx docs to do the same. 

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/1742
- [ ] Port libcudacxx docs to use Sphinx
- [ ] https://github.com/NVIDIA/cccl/issues/317
```
