### ISSUE TITLE
[FEA]: Overhaul libcudacxx NVRTC testing infrastructure

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#318]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

libcu++

### Is your feature request related to a problem? Please describe.

The existing libcudacxx NVRTC testing infrastructure is problematic because the build/test are inseparable steps, which means it can only be done on a machine with a GPU.

### Describe the solution you'd like

Ideally, splitting the compilation and execution into stages that match what `lit` expects would resolve the issue.

To do this we need:

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/465
- [x] Likely remove any special sauce for NVRTC configs in `lit`.
- [x] Launch builds with the above utility, `lit` can examine this for build failures just like `nvcc`/`gcc`
- [x] Launch tests as above, but instead it will find previously built fatbins/ptx and execute those TUs. (if executing tests is enabled)
```

This should be an evolution on top of the current NVRTC testing scripts/hacks, but made more general.

**Comment by wmaxey** [comment]
Marking as closed! This is done.
