### ISSUE TITLE
[FEA]: Reduce CI matrix for examples

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#342]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Infrastructure

### Is your feature request related to a problem? Please describe.

Currently, the `examples` job that builds/runs all of the examples from the `cccl/examples/` directory runs on the full nvcc matrix, including separate jobs for each of the C++ dialects. This is an excessive number of jobs for the examples, especially since things like the C++ dialect don't really impact the examples.

### Describe the solution you'd like

Similar to what was done for `nvrtc` here https://github.com/NVIDIA/cccl/blob/655fb8ecac5c25a1063fa78d93ec70d6df1484f3/ci/matrix.yaml#L48-L49

we should add a specific sub-matrix for the examples like:
```
 examples:
   - {cuda: *cuda_oldest, os: 'ubuntu18.04', cpu: 'amd64', compiler: {name: 'gcc', version: '12', exe: 'g++'}, gpu_build_archs: '70', std: [17]}
```

```[tasklist]
### Tasks
- [ ] Determine the relevant environment fields for running examples
- [ ] Determine relevant matrix for running examples
- [x] Add `examples:` sub-matrix to `matrix.yml`
- [x] Add `compute-examples-matrix` job to compute the matrix from the `matrix.yml`
- [x] Update the `examples` job to get its matrix from the `compute-examples-matrix` job
```
