### ISSUE TITLE
[FEA]: Add CI jobs for clang as a CUDA compiler

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#344]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

General CCCL

### Is your feature request related to a problem? Please describe.

While `clang` is not an officially support CUDA compiler, it is frequently used as such by many users. Ideally, CCCL should invest some effort to catch low hanging fruit and avoid breaking this use case on a best-effort basis. 

Ensuring CCCL compiles correctly with clang is also important for ensuring compatibility with tooling like `clangd` or `clang-tidy`. 

### Describe the solution you'd like

We should add jobs that compile/run libcu++/Thrust/CUB tests using the latest version of clang as a CUDA compiler.

```[tasklist]
### Tasks
- [ ] Add cmake preset to build CUB with clang
- [ ] Add cmake preset to build Thrust with clang
- [ ] Add cmake preset to build libcu++ with clang
- [ ] Add job to build/run CUB tests with clang
- [ ] Add job to build/run Thrust tests with clang
- [ ] Add job to build/run libcu++ tests with clang
```
