### ISSUE TITLE
[FEA]: Unify versioning macros

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#373]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

General CCCL

### Is your feature request related to a problem? Please describe.

I would like all of the relevant version macros across libcudacxx/thrust/cub to use a consistent source of truth. 

### Describe the solution you'd like

```[tasklist]
### Tasks
- [ ] Decide where to put the CCCL version definition
- [ ] Add `CCCL_VERSION` macro
- [ ] Update `THRUST_VERSION` to alias `CCCL_VERSION`
- [ ] Update `CUB_VERSION` to alias `CCCL_VERSION`
- [ ] https://github.com/NVIDIA/cccl/issues/372
- [ ] Update `LIBCUDACXX_VERSION` to use `CCCL_VERSION` 
``` 

I'm not sure where we would put the header that contains `CCCL_VERSION`. `cccl/cccl/version.h` would be an obvious choice, but the top level `cccl/` is not part of the include path when linking against our cmake targets.
