### ISSUE TITLE
[EPIC] Fork/Join Parallel Ranges

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#44]
Looking towards the future of C++ parallel algorithms, `<ranges>` are becoming the canonical model for expressing and composing algorithms with arbitrary transformations. As such, we want the next generation of Thrust/CUB-like parallel algorithms to be based on ranges.

Thus far, `<ranges>` has been designed primarily with sequential execution in mind. In order for us to build a next generation set of parallel algorithms and utilities, we will need to investigate to what extent the existing `<ranges>` design supports parallel execution. 

The high-level goal is that we should be able to use a ranges-based interface to express anything we are able to express today with Thrust + fancy iterators with equal or better expressiveness and performance. 

- [ ] https://github.com/NVIDIA/cccl/issues/45
- [ ] https://github.com/NVIDIA/cccl/issues/48
- [ ] https://github.com/NVIDIA/cccl/issues/1213
- [ ] https://github.com/NVIDIA/cccl/issues/1183
- [ ] https://github.com/NVIDIA/cccl/issues/1184
