### ISSUE TITLE
[EPIC]: Set up automatic and consistent code formatting with `clang-format`

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#455]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Infrastructure

### Is your feature request related to a problem? Please describe.

As a CCCL maintainer, I would like code formatting to be consistent across all of the CCCL files. Furthermore, enforcing the code formatting should be convenient and automatic. 

### Describe the solution you'd like

Use `clang-format` to apply consistent and automated formatting. 

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/461
- [ ] https://github.com/NVIDIA/cccl/issues/544
- [ ] https://github.com/NVIDIA/cccl/issues/456
- [x] Apply the agreed upon `.clang-format` file to entire CCCL code base
- [ ] https://github.com/NVIDIA/cccl/issues/1622
- [ ] https://github.com/NVIDIA/cccl/issues/1623
```

**Comment by miscco** [comment]
Do we really need a singular clang-format file? I believe it would suffice to have one for cub / thrust / libcudacxx each in their respective top level folders.

I agree that it would be better to have one unique code style, but especially libcu++ has some unique requirements due to it being a standard library with a ton of macros sprinkled around everywhere

**Comment by jrhemstad** [comment]
Thanks @bdice and @miscco !
