### ISSUE TITLE
[EPIC]: Thrust/CUB shouldn't invoke user-defined operators on out-of-bounds data

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#459]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

General CCCL

### Is your feature request related to a problem? Please describe.

As a user of Thrust/CUB, I can provide a custom operator to the many algorithms. My operator may only be defined for the values that are present in the input. As a result, it can be problematic if that operator is invoked on any of values, including uninitialized values. 

However, there have been numerous reports of Thrust/CUB algorithms invoking user-defined operators on uninitialized or otherwise out-of-bound values. See:
- https://github.com/NVIDIA/thrust/issues/1479
- https://github.com/NVIDIA/thrust/issues/1525
- https://github.com/NVIDIA/thrust/issues/1813
- https://github.com/NVIDIA/cccl/issues/458

I believe this is because the CUDA algorithm implementations within Thrust and CUB will have threads in a block do things like default construct objects or read past boundaries even if they don't ultimately participate in the work of the algorithm which can ultimately lead to problems like this. This is _fine_ for simple operators like `+`, but for custom operators it can cause failures. 

### Describe the solution you'd like

We should eliminate all cases where Thrust/CUB algorithms will invoke user-defined operators on out-of-bounds or uninitialized values. 

```[tasklist]
### Tasks
- [ ] Verify root cause of issue 
- [ ] Identify affected algorithms
- [ ] Design solution to avoid reading out of bounds elements
- [ ] Update affected algorithms with decided upon solution
```

**Comment by jrhemstad** [comment]
I think we can solve this similarly to how I described here: https://github.com/NVIDIA/cccl/issues/1662#issuecomment-2075009311

**Comment by sarda-devesh** [comment]
Coming to this epic from #3890. I am just wondering if there is a plan to include a warning about this in the [cub docs](https://nvidia.github.io/cccl/cub/api/structcub_1_1DeviceReduce.html#_CPPv4I0000000EN3cub12DeviceReduce11ReduceByKeyE11cudaError_tPvR6size_t18KeysInputIteratorT21UniqueOutputIteratorT20ValuesInputIteratorT25AggregatesOutputIteratorT22NumRunsOutputIteratorT12ReductionOpT9NumItemsT12cudaStream_t) while this issue is being resolved? The docs make it seem like the reduction operator only gets called for passed in values but if that is not the case then that should be documented somewhere so that users can write their code keeping that in mind.
