### ISSUE TITLE
[FEA]: Port Thrust benchmarks into CCCL repo

### ISSUE THREAD

**Issue by senior-zero** [NVIDIA/cccl#473]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Thrust

### Is your feature request related to a problem? Please describe.

We currently have a separate project containing Thrust benchmarks. The separation of benchmarks from the main repository doesn't allow us to reuse exiting infrastructure. 

### Describe the solution you'd like

All existing Thrust benchmarks are ported to CCCL repository:

```[tasklist]
### Tasks
- [x] Remove `thrust::device_vector` dependency from NVBench generators helper library API
- [x] Implement infrastructure for heterogeneous Thrust benchmarking
- [x] Add more tests for generators
- [x] Port `thrust_benchmark` benches
- [x] Implement benchmark runner script
```

```[tasklist]
### Deferred
- [ ] Hoist NVBench generators helper library to CCCL level
```

**Comment by senior-zero** [comment]
Moved tasks not related to porting thrust benchmarks into https://github.com/NVIDIA/cccl/issues/557
