### ISSUE TITLE
[EPIC]: CUB large input support

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#50]
As a lower-level interface, CUB should optimize for flexibility and performance. As a result, CUB will not guarantee a large input will work by default. However, it should enable users to specify their desired offset type.

This means CUB should not perform any dynamic dispatch based on the input size. Instead, users should have a way to statically specify the offset type. In [previous discussion](https://github.com/NVIDIA/cub/issues/212#issuecomment-929547156) we favored making the type of `num_items` a template and infer the offset type from the type of `num_items`. 
### Design-related research
- [x] https://github.com/NVIDIA/cccl/issues/1408
- [x] https://github.com/NVIDIA/cccl/issues/1454

### Testing large number of items
- [x] https://github.com/NVIDIA/cccl/issues/2139
- [x] https://github.com/NVIDIA/cccl/issues/2140
- [x] Add tests for large number of items in `DeviceScan::*ByKey`

### Enable large `num_items` in CUB algorithms that are sensitive to the choice of `offset_t`
- [x] https://github.com/NVIDIA/cccl/issues/2062
- [x] https://github.com/NVIDIA/cccl/issues/2458
- [x] https://github.com/NVIDIA/cccl/issues/1422
- [x] https://github.com/NVIDIA/cccl/issues/1437
- [x] https://github.com/NVIDIA/cccl/issues/2442
- [x] https://github.com/NVIDIA/cccl/issues/2515
- [x] https://github.com/NVIDIA/cccl/issues/2714
- [x] #3132
- [x] #3134
- [x] #3133
- [ ] https://github.com/NVIDIA/cccl/issues/2522
- [x] #3242
- [x] https://github.com/NVIDIA/cccl/issues/2521
- [x] https://github.com/NVIDIA/cccl/issues/2520
- [x] #3622
- [ ] ~~Add support for large `num_items` to `device_spmv.cuh`~~

### Limit the number of kernel template instantiations by reducing the set of offset types 
- [x] #3312

### Clean up interim testing infrastructure
- [x] Switch tests for large number of items to use `Device*` interface in `DeviceSelect`
- [x] Switch tests for large number of items to use `Device*` interface in `DeviceScan`

### Documentation
- [x] We want to be explicit about supported and tested offset types in the `Dispatch` interface (see https://github.com/NVIDIA/cccl/pull/1817#discussion_r1670650317)

**Comment by elstehle** [comment]
**legend for offset type:** ✅ considered done | 🟡 considered lower priority | 🟠 considered higher priority, as it prevents usage for larger-than-`INT_MAX` number of items | ⏳  in progress

**legend for testing columns:** ✅ considered done | 🟡 to be done | 🟠 needs to support wider offset types first

| algorithm                         |   offset type                                                                                                                                                                                                                          | tests larger-than`INT_MAX`                  | tests close to `[U]INT_MAX` |
|-----------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------|---------------------|
| `device_adjacent_difference.cuh`  | ✅ `choose_offset_t`                                                                                                                                                                                                         | ✅ 2^33, sanity check, iterators | 🟡                   |
| `device_radix_sort.cuh`           | ✅ `choose_offset_t`                                                                                                                                                                                                         | ✅ extensive check               | ✅ extensive check   |
| `device_reduce.cuh`               | ✅ `choose_offset_t`: `Reduce`, `Sum`, `Min`, `Max`, `ReduceByKey`, `TransformReduce` <br>  ✅ streaming: `ArgMin`, `ArgMax` (https://github.com/NVIDIA/cccl/pull/2647) ⚠️ (note: [new interface only)](https://github.com/NVIDIA/cccl/pull/3148)                             | ✅ sanity, 2^{30,31,33)          | ✅ sanity, 2^32-1    |
| `device_scan.cuh`                 | ✅ choose_offset_t: DeviceScan <br> ✅ choose_offset_t: DeviceScanByKey                                                                                                                                                                                                                     | ✅                               | ✅                   |
| `device_select.cuh`               | ✅ `choose_offset_t`: `UniqueByKey` <br> ✅ `streaming` (for any user-provided offset type): `Flagged`, `If`,  `Unique` (https://github.com/NVIDIA/cccl/pull/2400)                                                                                                             | ✅                               | ✅                   |
| `device_partition.cuh`            | ✅ `streaming` (for larger-than-int user-provided offset types): `Flagged`, `If` (https://github.com/NVIDIA/cccl/pull/2400) <br>  ✅ `streaming` (for larger-than-int user-provided offset types): `ThreeWayPartition` https://github.com/NVIDIA/cccl/pull/2506                                                                                                           | ✅ <br>✅                                | ✅ <br>✅                   |
| `device_segmented_sort.cuh`       | ✅  `num_segments`: supporting up to `int64_t` segments, chunked into `INT_MAX` number of segments per invocation (https://github.com/NVIDIA/cccl/pull/3308/) <br>  ✅  `num_items`: supporting up to `int64_t` items per segment                                                                                                                                                                                      | ✅                                | ✅                    |
| `device_merge_sort.cuh`           | ✅ choose_offset_t (https://github.com/NVIDIA/cccl/pull/3328)                                                                                                                                                                                                              | ✅ extensive check               | ✅ extensive check   |
| `device_transform.cuh`            | ✅ `choose_signed_offset_t` (https://github.com/NVIDIA/cccl/pull/3172)                                                                                                                                                                                                                   | ✅                               | ✅                  |
| `device_for.cuh`                  | ✅ `NumItemsT`: ForEachN, ForEachCopyN, Bulk <br> `difference_type`: ForEach, ForEachCopy                                                                                                                                     | 🟡                               | 🟡                   |
| `device_segmented_radix_sort.cuh` | ✅ `num_segments`: supporting up to `int64_t` segments (streaming https://github.com/NVIDIA/cccl/pull/3402)<br> ✅  `segment_offsets` & `num_items`: supporting up to `int64_t` (https://github.com/NVIDIA/cccl/pull/3402)<br> 🟡 `"segment_size"`: any single segment size may not exceed `INT_MAX`                                                                                                                                                 | ✅                               | ✅                   |
| `device_merge.cuh`                | ✅  `int64`: (perf for i32 and i64 was on par: https://github.com/NVIDIA/cccl/pull/3530)                                                                                                                                                                                                                    | ✅                               | ✅                  |
| `device_copy.cuh`                 | ✅`num_ranges`: `int64_t` (streaming approach, using uint32 with 512 M items at a time, see https://github.com/NVIDIA/cccl/pull/4129) <br> ✅`buffer sizes`: `iterator_traits<SizeIteratorT>::value_type`                                                                                                                                | ✅                               | ✅                   |
| `device_memcpy.cuh`               | ✅ `num_buffers`: `int64_t` (streaming approach, using uint32 with 512 M items at a time, see https://github.com/NVIDIA/cccl/pull/4065) <br> ✅ `buffer sizes`: `iterator_traits<SizeIteratorT>::value_type`                                                                                                                              | ✅                               | ✅                   |
| `device_histogram.cuh`            | 🟡 dynamic dispatch: int for (num_rows * row_stride_bytes)<INT_MAX; <br> OffsetT otherwise                                                                                                                                   | 🟡                               | 🟡                   |
| `device_segmented_reduce.cuh`     | ✅ `common_iterator_value_t({Begin,End}OffsetIteratorT)`: `Reduce`, `Sum`, `Min`, `Max` <br> ⚠️ [(note)](https://github.com/NVIDIA/cccl/pull/414#discussion_r1330632615) `int`: `ArgMin`, `ArgMax` <br> ✅ `num_segments`: `int64_t (streaming)` (https://github.com/NVIDIA/cccl/pull/3764) | ✅ sanity, rnd [2^31; 2^33]      | ✅                    |
| `device_run_length_encode.cuh`    | ✅ `streaming` (for larger-than-int user-provided offset types), else just use non-streaming with int32 offset type                                                                                                                                                                                                                     | ✅                               | ✅                   |

**Comment by elstehle** [comment]
Note, this issue is can be considered complete with two minor exceptions. There are just two CUB algorithms that currently do not yet fully support large number of items:
- `DeviceSegmentedRadixSort` does not support any single segment size larger than `INT_MAX` as that would degrade performance. Moreover, `DeviceSegmentedSort` is the algorithm of choice for such large segments, as `DeviceSegmentedRadixSort` does not load balance between segments.
- `DeviceSegmentedReduce::Arg{Min,Max}` does not support large offsets due to the issue referenced in [this comment](https://github.com/NVIDIA/cccl/pull/414#discussion_r1330632615).

I will leave this issue open for now, until `DeviceSegmentedReduce::Arg{Min,Max}` is resolved.
