### ISSUE TITLE
[THEME] CCCL Unification

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#52]
# Summary

[Thrust](https://github.com/NVIDIA/thrust), [CUB](https://github.com/NVIDIA/cub), and [libcu++](https://github.com/NVIDIA/libcudacxx) comprise the Core CUDA C++ Libraries (CCCL). They strive to serve a similar role to the Standard C++ Library for Standard C++ in that they provide standard, general purpose tools for writing speed-of-light CUDA C++ applications.

For historical reasons, these libraries each have their own repository and naively give the impression that they are independent. However, for years there has been a cyclical dependency between CUB and Thrust. Likewise, both Thrust and CUB increasingly depend on libcu++.

This false independence frequently causes confusion to users (e.g., people often expect they can pull a custom version of CUB without updating Thrust). Likewise, it increases developer burden to maintain infrastructure across three repositories. 

We would like unify the CCCL components to make it easier for both users and maintainers. This will be a long term effort that starts with merging the three separate repositories into one at github.com/nvidia/cccl. We will then start consolidating various GitHub and code infrastructure including unifying the docs have a common look and feel consistent with the CUDA programming guide. 

# Intended Outcome

Our initial goal is to make it easier to use and maintain Thrust/CUB/libcu++.  

We also want to start shifting people's mental model of Thrust/CUB/libcu++ as independent libraries and instead think of them as if they were different components of the same library.

Out ultimate goal is to one day have a singular Core CUDA C++ Library (CCCL) that subsumes all of the functionality of Thrust, CUB, and libcu++. Similar to the Standard Library in Standard C++, CCCL will provide all of the general purpose building blocks CUDA C++ developers need to create speed-of-light applications. 

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/40
- [ ] https://github.com/NVIDIA/cccl/issues/51
- [x] Write blog post explaining rationale, what is changing, and what to look forward to
```

# Related Info

**Comment by jrhemstad** [comment]
Docs overhaul is still in progress, but closing this issue as I think its usefulness as a separate tracking issue has ended.
