### ISSUE TITLE
Experiment with proof-of-concept for native Windows support for Actions Runner Controller

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#521]
Our self-hosted GitHub runners rely on using [Actions Runner Controller](https://github.com/actions/actions-runner-controller) on top of a Kubernetes cluster. 

In order to support self-hosted Windows runners, we'll need to figure out how to get Windows working with ARC. 

```[tasklist]
### Tasks
- [x] Setup K8s cluster on a local Windows machine
- [x] Set up control node in WSL on local Windows machine
- [x] Deploy a K8s pod that runs a web server with "Hello World"
- [x] Figure out how to integrate ARCv2 w/ K8s cluster on Windows
- [ ] Submit PR to RAPIDS action runner image repo that adds Windows runner image
- [ ] Summarize everything that was done for the PoC in comment on this issue
```

**Comment by jrhemstad** [comment]
This is blocked until we've investigated the self-hosted runner transition to use Windows VMs on Linux Host OS.

**Comment by jrhemstad** [comment]
Superseded by https://github.com/NVIDIA/cccl/issues/1264
