### ISSUE TITLE
Specialize relevant `cuda::(std::)` types for `__half/bfloat16/fp8`

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#525]
The CUDA extended floating point types [`__half`](https://docs.nvidia.com/cuda/cuda-math-api/struct____half.html#struct____half) and [`__nv_bfloat16`](https://docs.nvidia.com/cuda/cuda-math-api/struct____nv__bfloat16.html#struct____nv__bfloat16) and fp8 (and others) are important types for many CUDA C++ developers.

As a CUDA C++ developer, I'd like it if relevant CCCL utilities like `<type_traits>`, `atomic<T>`, `complex<T>` all worked with these types.

### Tasks
- [x] https://github.com/NVIDIA/cccl/issues/1139
- [ ] #3044
- [ ] #3349
- [ ] Specializations for `<type_traits>`
- [ ] Specializations of complex<T> for fp8?
- [ ] Specializations for `atomic<T>`
- [ ] Overloads for <cmath> functions for cudart extended floating-point types
- [ ] Implement `cub::Traits` in terms of the new `<type_traits>`
- [ ] Deprecate `cub::Traits`

**Comment by srinivasyadav18** [comment]
Hi @jrhemstad, 
This looks like an interesting issue to me. I would like to contribute to this Issue.

**Comment by jrhemstad** [comment]
Hey @srinivasyadav18, thanks for your interest in helping make CCCL better!

@griwes was just starting to look into this issue. He'll have a better idea of the details of what will be required and what parts you could help out with. For example, specializing `complex` vs `<type_traits>` will be different tasks.

**Comment by srinivasyadav18** [comment]
@jrhemstad Thanks! I will coordinate with @griwes to see what I can help. 
I have done some initial work enabling `type_traits` for **__half** and **__nv_bfloat16**, I will share the link to the branch in some time soon.

**Comment by srinivasyadav18** [comment]
Hi @griwes, I made these initial [changes](https://github.com/NVIDIA/cccl/compare/main...srinivasyadav18:cccl:fea525) which enables **__half** and **__nv_bfloat16**. I am exactly not sure if it is the right way to include <cuda_fp16.h> and <cuda_bf16.h> in `__type_traits/is_floating_point.h`. Please let me know if I am missing anything here. Thanks! :)

**Comment by jrhemstad** [comment]
> I am exactly not sure if it is the right way to include <cuda_fp16.h> and <cuda_bf16.h> in __type_traits/is_floating_point.h

I'm guessing we're going to have to be more careful about how we include those headers because we support versions of the CTK that may not have those headers yet. So it'll require some careful ifdefs. Here's an example from CUB: https://github.com/NVIDIA/cub/blob/0fc3c3701632a4be906765b73be20a9ad0da603d/cub/util_type.cuh#L43C1-L48

@miscco @gevtushenko may be able to help figure out the right way to guard including those headers.

**Comment by ngc92** [comment]
`std::numeric_limits<half>` would be quite handy in several places. Even rolling your own is not really possible, because of the lack of constexpr constructors for half and bfloat16.

**Comment by bernhardmgruber** [comment]
> [@gevtushenko](https://github.com/gevtushenko) says that CUB already has some of the relevant values for `<limits>` that can be used.

Yes, this is `cub::Traits` from [`util_type.cuh`](https://github.com/NVIDIA/cccl/blob/87f72468ba4a094ab03d0f901d670c261a2e9e6e/cub/cub/util_type.cuh). We should deprecate and replace it by `<cuda/std/type_traits>` when it's ready.

**Comment by miscco** [comment]
Yes see https://github.com/NVIDIA/cccl/pull/2749 where I started adding more implementations for extended floating point types

**Comment by fbusato** [comment]
Adding extended floating-point to `cuda::std::numeric_limits` is not straightforward. Many operations are not even `constexpr` (contrary to the C++ standard)

**Comment by miscco** [comment]
> Hello team, Can we add overloads of `cuda::std::frexp` for the extended floating point types? This is needed in the case of pytorch `frexp_cuda`. See [pytorch/pytorch#133313](https://github.com/pytorch/pytorch/pull/133313)

I am adding those [here](https://github.com/NVIDIA/cccl/pull/3382)

**Comment by fbusato** [comment]
what is the meaning of `Overloads for functions for cudart extended floating-point types`?

**Comment by jrhemstad** [comment]
> what is the meaning of `Overloads for functions for cudart extended floating-point types`?

"cudart extended floating-point types" just means the `__half/bfloat` types that exist today in the CUDA headers.

I think the item about adding overloads for functions was just a catch-all for anything else that wasn't listed, like adding overloads for `cmath` functions, etc. This item should definitely be defined and broken up into more detailed tasks.
