### ISSUE TITLE
[EPIC] Implement VSMem abstraction

### ISSUE THREAD

**Issue by senior-zero** [NVIDIA/cccl#548]
Porting of Thrust algorithms to CUB is blocked by a lack of VSMem abstraction. In Thrust, when a thread block can't fit temporary storage in the default shared memory size, it'll switch to using per-CTA global memory tiles. Introducing a pointer to shared memory in CUB kernels leads to performance regressions because generic loads are used instead of shared or global ones. 

To avoid regressions, we must implement functionality allowing the processing of user-defined types of any size. It doesn't have to match the agent approach from Thrust or use global memory as long as the requirements are satisfied. 

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cub/issues/713
- [ ] https://github.com/NVIDIA/cub/issues/747
- [ ] Integrate this approach to unique by key (https://github.com/NVIDIA/cccl/issues/159)
```

**Comment by elstehle** [comment]
Closing this EPIC, as the last task of this EPIC was completed with PR https://github.com/NVIDIA/cccl/pull/1197
