### ISSUE TITLE
[FEA]: Transition to new Thrust benchmarks

### ISSUE THREAD

**Issue by senior-zero** [NVIDIA/cccl#557]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Thrust

### Is your feature request related to a problem? Please describe.

We have to remove thrust/internal/benchmark/bench.cu and rely on new Thrust benchmarks instead.

### Describe the solution you'd like

```[tasklist]
### Tasks
- [ ] Transition internal perf testing to new benchmarks
- [ ] Remove old benchmarks
- [ ] Enable building Thrust benchmarks in CI
```

**Comment by bernhardmgruber** [comment]
Please add a `thrust.all.benches` target like we have for CUB, thx!
