### ISSUE TITLE
[EPIC] `cuda::ptx` platform for exposing PTX instructions

### ISSUE THREAD

**Issue by ahendriksen** [NVIDIA/cccl#573]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

libcu++

### Is your feature request related to a problem? Please describe.

The development of higher-level APIs lags behind the introduction of new PTX instructions in the CUDA Toolkit. 

### Describe the solution you'd like

Provide a means to add PTX instructions before higher-level exposure has been developed.

That is:
- Add the header `cuda/ptx`
- Add the namespace `cuda::ptx`
- Add PTX instructions to expose cluster-level and other features.

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/616
- [ ] https://github.com/NVIDIA/cccl/issues/609
``` 

### Describe alternatives you've considered

The alternative is to wait for higher-level exposure, which may take a while. 

Another alternative is to provide an intermediate exposure like the recent addition of `cuda::device::experimental::cp_async_bulk_global_to_shared` and friends. These wrapper functions are a hybrid between pure PTX wrapping functions using native types, and higher-level APIs that take higher-level types (like `cuda::barrier<..>`). These are very useful for documenting features to outside developers, but require design and deviate from the PTX ISA.

**Comment by ahendriksen** [comment]
Closing this epic in favor of [a Hopper-specific epic](https://github.com/NVIDIA/cccl/issues/1340). The goal of setting up a platform for exposing PTX instructions has been achieved..
