### ISSUE TITLE
[EPIC] Design a scheme allowing CUB to process user-defined types of any size

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#612]
This issue describes a subtask of https://github.com/NVIDIA/cccl/issues/548 with the goal of identifying and prototyping a solution that helps us avoid running into situation where we try to allocate more shared memory than is available. 
```[tasklist]
### Tasks
- [x] Look into current vshmem implementations (i.e., thrust and cub's MergeSort)
- [x] ~Consider adding a limit to sizeof input type to CUB/Thrust algorithms~ (Won't do this)
- [x] Decide between using global memory (Thrust) as shared overflow vs reducing tile size (CUB) (or mixture)
- [x] Verify existing CUB merge sort only emits a single kernel
- [x] Benchmark using a single backup configuraiton (IPT, TPB) that has small tile size versus using vshmem
- [x] Decide whether to increase shared memory carve-out
- [ ] https://github.com/NVIDIA/cccl/issues/553
```

## Rationale
> Consider adding a limit to sizeof input type to CUB/Thrust algorithms:

Decision: We won't add a limit to sizeof input. We prefer to enable users when possible rather than breaking compilation, even if this results in subpar performance of the corner case, as long as this does not have a negative effect on the performance of the common use case.

> Benchmark using a single backup configuraiton (IPT, TPB) that has small tile size versus using vshmem

I had run an experiment for this by adapting `DeviceMergeSort` with a large type and using a _small tile size-fallback configuration_ turned out to be a promising path for the middle ground of user-provided types before having to default to gmem-backed vshmem. 

> Decide whether to increase shared memory carve-out

Given that we will treat the middle ground with a fallback configuration that uses a smaller tile size, we do not want to further complicate the implementation and introduce yet another code path for wht is presumably likely just a small niche of use cases.

## Design Considerations
- Make sure we need to compile only a single kernel template specialisation instead of run-time dispatching to a vshmem or a non-vshmem kernel instance.
- Make sure a non-vshmem kernel template instance emits ld/st.shared rather than generic load/stores
