### ISSUE TITLE
[FEA]: Implement iterator concepts and update `<iterator>` to C++20

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#62]
`<ranges>` require a lot of machinery in place to work. This includes the various concepts, e.g. `std::contiguous_iterator` but also iterator traits.

As a first step of the `<ranges>` implementation we should implement those and update all the machinery in `<iterators>`
```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/206
- [ ] https://github.com/NVIDIA/cccl/issues/247
- [ ] https://github.com/NVIDIA/cccl/issues/337
- [ ] https://github.com/NVIDIA/cccl/issues/366
- [ ] https://github.com/NVIDIA/cccl/issues/382
- [ ] https://github.com/NVIDIA/cccl/issues/384
- [ ] https://github.com/NVIDIA/cccl/issues/444
- [ ] https://github.com/NVIDIA/cccl/issues/463
- [ ] https://github.com/NVIDIA/cccl/issues/470
- [ ] https://github.com/NVIDIA/cccl/issues/483
- [ ] https://github.com/NVIDIA/cccl/issues/495
- [ ] https://github.com/NVIDIA/cccl/issues/505
- [x] Implement `__bounded_iter`
- [ ] https://github.com/NVIDIA/cccl/issues/545
- [ ] https://github.com/NVIDIA/cccl/issues/610
- [ ] Implement `ranges::prev`
- [ ] Implement `ranges::distance`
- [ ] Modernize `move_iterator`
- [ ] Cleanup `<iterator>`
- [ ] Modernize `reverse_iterator`
- [ ] Modernize `wrap_iter`
```

**Comment by miscco** [comment]
Done with #627
