### ISSUE TITLE
[FEA]: Avoid relative includes in all CCCL headers

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#641]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

General CCCL

### Is your feature request related to a problem? Please describe.

I would like all CCCL headers to avoid relative includes as this improves integration with NVRTC runtime compilation. 

### Describe the solution you'd like

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/631
- [ ] Remove relative includes from Thrust
- [ ] Remove relative includes from libcudacxx
- [ ] Implement a CI check for relative includes 
```

**Comment by wmaxey** [comment]
Did I miss a discussion about this? How do relative includes make NVRTC compilation difficult? Is it an issue under`jitify`?

I particularly enjoy not writing `<cuda/std/detail/libcxx/__feature/__include>` and would need to see good reason for it.

**Comment by jrhemstad** [comment]
@leofang since I believe this was a request originally from you, would you mind summarizing why relative includes are undesirable when using NVRTC?

**Comment by miscco** [comment]
I believe there was an internal discussion about it and we found that it would break our libcxx tests, as we cannot use the full path there

**Comment by YdrMaster** [comment]
I have encountered the same problem. I‘m using rust to call nvrtc and compile kernel with cccl/cub. cccl is included as a git submodule in one of the rust crate. When I use this crate locally, everything is fine. But when I use crate in cargo cache, many relative includes just fail to open. I believe this is because the relative path is expanded into a complex form on Windows, which contains characters that nvrtc can't handle.

```plain
... .cargo\git\checkouts\cuda-bench-d5429c20210451e4\7d3f9f9\cuda\cccl\libcudacxx/include/cuda/std/detail/libcxx/include/__functional/../__utility/../__fwd/../__concepts/../__concepts/../__concepts/../__concepts/../__type_traits/is_convertible.h(31): catastrophic error: cannot open source file "../__utility/declval.h"
  #include "../__utility/declval.h"
```

**Comment by miscco** [comment]
We are currently in the process of adopting our structure to get rid of relative includes, but that is not a small undertaking

**Comment by leofang** [comment]
> @leofang since I believe this was a request originally from you, would you mind summarizing why relative includes are undesirable when using NVRTC?

Sorry for my late reply. In the case of NVRTC + CCCL, the working bridge in-between is currently served by [Jitify](https://github.com/NVIDIA/jitify). What it does is it searches all `#include` statements in the source, patches out all std/system headers (to make NVRTC happy), and caches the patched source using the include path [as a key](https://github.com/NVIDIA/jitify/blob/9c01f4988bbc3e11fcb84fc2747b5d0f2af7862e/jitify.hpp#L577-L580). So for example, `<cuda/std/type_traits>` and `"std/type_traits"` would become two distinct entries, despite it’s the same header. Since this search-patch loop is quite expansive, it was preferable to retain this cache for as long as possible, only invalidated when CCCL is updated.

However, avoiding relative includes was just one of the options, we do not have to pursue if we go with other options (e.g. rewrite Jitify’s search logic or cache logic or both, or drop Jitify in favor of another bridge, or whatever). I don’t have a clear thought/opinion so far. It could also be possible that the entire CCCL now just works with NVRTC without Jitify, which would be the best scenario.

**Comment by miscco** [comment]
We recently dropped our libcxx support, so I believe we can go forward with an actual solution to this issue by moving towards a sane folder structure.

That said, I would wait until 2.4.x is finalized before starting such a large refactoring

**Comment by miscco** [comment]
Actually now that we dropped libcxx compilation support we can directly switch to absolute includes and move the files later.
