### ISSUE TITLE
First pass of CCCL docs overhaul

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#642]
This issue tracks the MVP of the initial docs update. The goal is to just get the docs built and hosted as-is from the nvidia/cccl repo on nvidia.github.io/cccl and set up link redirection so existing links to the old docs sites continue to work. 

https://nvidia.github.io/libcudacxx/
https://nvidia.github.io/thrust/
https://nvlabs.github.io/cub/

[How to redirect a GitHub pages URL](https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7)

```[tasklist]
### Tasks
- [x] Build and host existing docs under nvidia.github.io/cccl/lib
- [x] Create minimal landing page under nvidia.github.io/cccl with links to each lib docs
- [x] Setup URL redirection from nvidia.github.io/lib to nvidia.github.io/cccl/lib
```
