### ISSUE TITLE
[FEA]: Create a script to update the library version number eveywhere

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#645]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Infrastructure

### Is your feature request related to a problem? Please describe.

As a maintainer of CCCL, I would like an easy and consistent way to update the library version number in all the relevant headers and config files (e.g., cmake). 

### Describe the solution you'd like

I would like a script `ci/update_version.sh` that I can provide a version number and it will automatically make the changes to the necessary files to update the version. For example:

```
ci/update_version.sh 2.3.0
```
This should update things like `_LIBCUDACXX_CUDA_API_VERSION_MAJOR`, `THRUST_MAJOR_VERSION`, etc. Some of the relevant things that need to change are documented here: https://github.com/NVIDIA/cccl#api-versioning

```[tasklist]
### Tasks
- [ ] Update libcudacxx version numbers
- [ ] Update CUB version numbers
- [ ] Update Thrust version numbers
- [ ] Update CMake version numbers?
``` 

### Additional context

Here's a similar script from RAPIDS cuDF: https://github.com/rapidsai/cudf/blob/branch-23.12/ci/release/update-version.sh
