### ISSUE TITLE
[EPIC] Document support and compatibility guarantees

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#66]
# Summary

CCCL users need to know what environments we support to compile and execute our code. 

# Intended Outcome

We should provide clear and easy to find documentation that describes our support for:
- CUDA Toolkit versions
- Host compilers and versions
- GPU Architectures
- C++ Standard Versions

The documentation should include not only what we support today, but a deprecation policy for how that support will evolve over time (e.g., when will we drop C++ standards, etc.). 

```[tasklist]
# Tasks
- [ ] Document C++ Standard support and deprecation policy
- [ ] Document GPU Architecture support and deprecation policy
- [ ] Document Host compiler support and deprecation policy
- [ ] Document CUDA toolkit version support and deprecation policy
```

# Related Information

- Bryce previously wrote up a [proposal](https://github.com/NVIDIA/thrust/issues/916) for a compatibility policy of Thrust with older CTK versions that could be the basis for our CTK support policy 

- https://github.com/NVIDIA/libcudacxx/issues/322

**Comment by jrhemstad** [comment]
Something I just realized probably wasn't clear from previous discussions is that _new_ features don't need to be backported.

In short, if a feature worked with CTK X.Y when X.Y was released, then it should continue to work until we drop support for all of X.*.

If we introduce a feature with 11.5, there is no expectation that it needs to work with 11.4 or below. The exception would be if we use that feature internal to another feature that _is_ expected to work with 11.4 and below. 

In my ideal world we would have a per header (or even per function) annotation that shows the minimum supported CTK/C++ Standard, similar to what cppreference does for C++ standard support

![latest-screenshot](https://user-images.githubusercontent.com/15221289/234333052-fa5d80f6-e865-4001-adc2-b95a6576788f.png)
