### ISSUE TITLE
Create and publish Windows docker container images

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#82]
@wmaxey prior work here: https://github.com/NVIDIA/libcudacxx/pull/405/files 

https://github.com/wmaxey/cuda-windows-images
```[tasklist]
### Tasks
- [x] Create Windows docker images that are sufficient to build/test CCCL
- [ ] [Merge the image definition/build infrastructure into rapidsai/devcontainers](https://github.com/rapidsai/devcontainers/pull/87)
- [ ] Publish images on rapidsai Dockerhub
```

**Comment by wmaxey** [comment]
https://github.com/wmaxey/libcudacxx/pull/2
