### ISSUE TITLE
Port CUB device-scope histogram and sort-related algorithm tests to use Catch2

### ISSUE THREAD

**Issue by elstehle** [NVIDIA/cccl#86]
```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/1381
- [ ] https://github.com/NVIDIA/cccl/issues/1268
- [ ] https://github.com/NVIDIA/cccl/issues/1380
- [ ] https://github.com/NVIDIA/cccl/issues/1211
```

**Comment by bernhardmgruber** [comment]
@elstehle is this done now that #1381 is merged?

**Comment by elstehle** [comment]
> @elstehle is this done now that #1381 is merged?

That's great, thank you for helping to get this over the finish line 👏
Closing the issue as completed.
