### ISSUE TITLE
CUB tests need improved compiler coverage

### ISSUE THREAD

**Issue by allisonvacanti** [NVIDIA/cccl#864]
# Milestone Target Summary

We currently do not test on all platforms that we support. We should test each supported major version of GCC, Clang, and MSVC. Thrust has decent coverage since DVS builds the Thrust tests and examples, but DVS does not know about CUB. We currently know that the CUB test harness cannot be built on GCC 5, see error below. 

## Deliverables

- [x] Manually validate Thrust/CUB and enable Thrust's gpuCI for the latest releases of:
    - GCC
      - [x] 5
      - [x] 6
      - [x] 7
      - [x] 8
      - [x] 9
      - [x] 10
    - Clang
      - [x] 6 (will deprecate)
      - [x] 7
      - [x] 8
      - [x] 9
      - [x] 10
    - MSVC:
      - [x] 2017 (will deprecate)
      - [x] 2019
- [x] Fix all compile and runtime issues identified by these tests.
- [ ] Add DVS coverage for CUB tests (Teach DVS to run our gpuCI containers?)
- [ ] Add gpuCI coverage for MSVC.
