### ISSUE TITLE
Port CUB device-scope selection, partition, and adjacent difference algorithm tests to use Catch2

### ISSUE THREAD

**Issue by elstehle** [NVIDIA/cccl#87]
```[tasklist]
### Tasks
- [x] `test/test_device_select_if.cu`
- [x] `test/test_device_adjacent_difference.cu`
- [x] `test/test_device_select_unique.cu`
- [ ] `test/test_device_run_length_encode.cu`
- [x] `test/test_device_select_unique_by_key.cu`
- [x] `test/test_device_three_way_partition.cu`
```

**Comment by senior-zero** [comment]
@elstehle the "Convert to issue" doesn't do anything for some reason. I'll port `test/test_device_three_way_partition.cu` if you don't mind.

**Comment by senior-zero** [comment]
Not all tests were ported, reopening.
